agent: ranjeetsee

trigger: none

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)\root'
    backendServiceArm: 'infra_test2'
    backendAzureRmStorageAccountName: 'stgranjeet'
    backendAzureRmContainerName: 'tfcontainer'
    backendAzureRmKey: 'tfstatefile'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)\root'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)\root'
    environmentServiceNameAzureRM: 'infra_test2'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)\root'
    environmentServiceNameAzureRM: 'infra_test2'
